---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: test-optimizer

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: test-optimizer
    newTag: latest

replicas:
  - name: test-optimizer
    count: 2