---
apiVersion: v1
kind: Namespace
metadata:
  name: test-optimizer
  labels:
    name: test-optimizer
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-optimizer-quota
  namespace: test-optimizer
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: test-optimizer-limits
  namespace: test-optimizer
spec:
  limits:
    - max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      type: Container